# Generated by Django 5.0 on 2023-12-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tamanhomassa_tamanhopizza_produto_tamanho_massa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamanhomassa',
            name='valor2_1_pessoa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tamanhomassa',
            name='valor2_2_pessoas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tamanhomassa',
            name='valor_1_pessoa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tamanhomassa',
            name='valor_2_pessoas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
