# Generated by Django 5.0 on 2023-12-05 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tamanhomassa_valor2_1_pessoa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanhomassa',
            name='valor2_1_pessoa',
        ),
        migrations.RemoveField(
            model_name='tamanhomassa',
            name='valor2_2_pessoas',
        ),
    ]
