# Generated by Django 5.0 on 2023-12-05 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_tamanhomassa_valor2_1_pessoa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho_pizza',
        ),
        migrations.AddField(
            model_name='produto',
            name='valorPizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.pizzas'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TamanhoPizza',
        ),
    ]
