# Generated by Django 5.0 on 2023-12-05 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pizzas_remove_produto_tamanho_pizza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valorPizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pizzas'),
        ),
    ]
