# Generated by Django 5.0 on 2023-12-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_nome_produto_nome_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamanhomassa',
            old_name='valor_1_pessoa',
            new_name='valor_massa',
        ),
        migrations.RemoveField(
            model_name='tamanhomassa',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='tamanhomassa',
            name='valor_2_pessoas',
        ),
    ]
