# Generated by Django 5.0 on 2023-12-05 16:57

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_valor_1_pessoa_tamanhomassa_valor_massa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorMassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_massa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValorRefriSucos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_refri_sucos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TamanhoMassa',
            new_name='ValorEsfihas',
        ),
        migrations.RenameField(
            model_name='valoresfihas',
            old_name='valor_massa',
            new_name='valor_esfihas',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tamanho_massa',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor',
        ),
        migrations.AddField(
            model_name='produto',
            name='valorEsfihas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=core.models.ValorEsfihas),
        ),
        migrations.AddField(
            model_name='produto',
            name='valorMassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.valormassa'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valorRefriSucos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.valorrefrisucos'),
        ),
    ]
