# Generated by Django 5.0 on 2023-12-05 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tipovalor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valorEsfihas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.valoresfihas'),
        ),
    ]
