# Generated by Django 5.0 on 2023-12-05 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_produto_valoresfihas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valorNovo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipovalor'),
        ),
    ]
