# Generated by Django 5.0 on 2023-12-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_produto_valornovo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipovalor',
            old_name='tipo_valor',
            new_name='valor_novo',
        ),
    ]
